#!/usr/bin/env bash

PROGNAME=${0##*/}

usage()
{
    cat <<EOF

Usage: $PROGNAME ROOT_PATH
Where ROOT_PATH is the path to check.

$PROGNAME will spider its way through ROOT_PATH looking for *.md5 and *.md5sum
files. It wil then compare them to similarly named files in the same directory.

This program expects files and their MDS5 checksums to be of the following
pattern:

   file.foo.bar
   file.foo.bar.md5

or:

   file.foo.bar
   file.foo.nar.md5sum

Will output a list of files which do not match their MD5 checksums, as well as
a list of any MD5 checksum files without matching files.

If no output, then you can assume there were no problems.
EOF
}

process()
{
  local RPATH=$1
  local EXT=$2
  local MD5_MISMATCH=()
  local FILENOTFOUND=()

  for F in $(find $RPATH -iname "*.${EXT}"); do
    local FB=${F%.*}
    if [ -f "$FB" ]; then
      local MD5SUM=$(md5sum $FB | cut -d " " -f 1 -)
      local CHECK_MD=$(cat $F)
      if [ "$MD5SUM" != "$CHECK_MD" ]; then
        MD5_MISMATCH+=($FB)
      fi
    else
      FILENOTFOUND+=($F)
    fi
  done

  # Now display errors
  if [ ${#MD5_MISMATCH[@]} -ne 0 ]; then
    echo ">>> THE FOLLOWING FILES HAD MISMATCHING MD5 CHECKSUMS!"
    for F in $MD5_MISMATCH; do
      echo $F
    done
  fi

  if [ ${#FILENOTFOUND[@]} -ne 0 ]; then
    echo ">>> THE FOLLOWING MD5 CHECKSUMS LACKED MATCHING FILES!"
    for F in $FILENOTFOUND; do
      echo $F
    done
  fi
}

if [ -n "$1" ]; then
  ROOT_PATH=$1
  if [ -d "$ROOT_PATH" ]; then
    process $ROOT_PATH "md5"
    process $ROOT_PATH "md5sum"
  else
    echo "Error! $ROOT_PATH does not exist!"
    usage
  fi
else
  echo "Usage error! Missing root path!"
  usage
fi
